name = "shortlink"
type = "webpack"

account_id = "97ad16f52fc63a5b8dcefd19e69d6ee3"
workers_dev = true
route = "curl.ssshinchannn.workers.dev/*"
compatibility_date = "2022-05-03"

kv_namespaces = [ 
  { binding = "shortlink", id = "dd09e4f4fa9a4fa7842df56d5a7a91c7" }
]
