name = "shortlink"
type = "webpack"

account_id = "2b6b6ce7e733aa5c5f548f89ae8a8b1f"
workers_dev = true
route = "dark-field-6def.f5.workers.dev/*"
zone_id = ""
compatibility_date = "2022-05-03"

kv_namespaces = [ 
  { binding = "shortlink", id = "fb25ca86743d4a10a5035d8972fbfa68" }
]